# Generated by Django 2.1.3 on 2018-11-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitallibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('fullname',)},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='fullname',
        ),
    ]
